#!/usr/bin/env python
"""
This is the main script of slam cli
"""

from core import api, arguments
from domains.view import SlamDomainView
from domains.controller import SlamDomainController
from networks.view import SlamNetworkView
from networks.controller import SlamNetworkController
from hardware.view import SlamHardwareView
from hardware.controller import SlamHardwareController
from hosts.controller import SlamHostController
from hosts.view import SlamHostView

args = arguments.SlamArgumentsParser()
session = api.SlamAPIController()
session.login()
view = None
ctrl = None

if args.plugin() == 'domains':
    view = SlamDomainView(session)
    ctrl = SlamDomainController(session)
elif args.plugin() == 'networks':
    view = SlamNetworkView(session)
    ctrl = SlamNetworkController(session)
elif args.plugin() == 'hardware':
    view = SlamHardwareView(session)
    ctrl = SlamHardwareController(session)
elif args.plugin() == 'hosts':
    view = SlamHostView(session)
    ctrl = SlamHostController(session)

if args.action() == 'list':
    view.list()
elif args.action() == 'show':
    view.show(args.options())
elif args.action() == 'create':
    ctrl.create(args.options())
elif args.action() == 'add':
    ctrl.add(args.options())
elif args.action() == 'update':
    ctrl.update(args.options())
elif args.action() == 'delete':
    ctrl.delete(args.options())
elif args.action() == 'remove':
    ctrl.remove(args.options())
