#!/usr/bin/env python

from core import api, arguments
from domains.view import SlamDomainView
from domains.controller import SlamDomainController
from networks.view import SlamNetworkView
from networks.controller import SlamNetworkController

args = arguments.SlamArgumentsParser()
session = api.SlamAPIController()
session.login()
view = None
ctrl = None

if args.plugin() == 'domains':
    view = SlamDomainView(session)
    ctrl = SlamDomainController(session)
elif args.plugin() == 'networks':
    view = SlamNetworkView(session)
    ctrl = SlamNetworkController(session)

if args.action() == 'list':
    view.list()

if args.action() == 'show':
    view.show(args.options())

if args.action() == 'create':
    ctrl.create(args.options())

if args.action() == 'add':
    ctrl.add(args.options())

if args.action() == 'update':
    ctrl.update(args.options())
